create table if not exists public.members (
  user_id text primary key,
  username text not null,
  avatar text,
  ip_address text,
  country text,
  region text,
  city text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  total_seconds bigint not null default 0,
  status text not null default 'active' check (status in ('active','limited','banned')),
  updated_at timestamptz not null default now()
);

create table if not exists public.member_sessions (
  id bigint generated by default as identity primary key,
  user_id text not null references public.members(user_id) on delete cascade,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_seconds bigint not null default 0
);

create table if not exists public.admin_actions (
  id bigint generated by default as identity primary key,
  admin_user_id text not null,
  target_user_id text,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text,
  message text not null,
  image_url text,
  author_avatar_url text,
  author_role text,
  author_user_id text not null,
  author_name text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  is_active boolean not null default true
);

create index if not exists members_last_seen_idx on public.members(last_seen_at desc);
create index if not exists sessions_user_idx on public.member_sessions(user_id, started_at desc);
create index if not exists announcements_active_idx on public.announcements(is_active, created_at desc);

alter table public.members enable row level security;
alter table public.member_sessions enable row level security;
alter table public.admin_actions enable row level security;
alter table public.announcements enable row level security;

-- O backend usa a chave secreta do Supabase; nenhum dado administrativo é exposto diretamente ao navegador.
revoke all on public.members from anon, authenticated;
revoke all on public.member_sessions from anon, authenticated;
revoke all on public.admin_actions from anon, authenticated;
revoke all on public.announcements from anon, authenticated;

-- Recomendado para o projeto: execute este arquivo no SQL Editor do Supabase.
-- A chave secreta nunca deve ser colocada no index.html ou no GitHub.

alter table public.members add column if not exists username text;
alter table public.members add column if not exists avatar text;
alter table public.members add column if not exists country text;
alter table public.members add column if not exists region text;
alter table public.members add column if not exists city text;
alter table public.members add column if not exists first_seen_at timestamptz default now();
alter table public.members add column if not exists last_seen_at timestamptz default now();
alter table public.members add column if not exists total_seconds bigint default 0;
alter table public.members add column if not exists status text default 'active';
alter table public.members add column if not exists updated_at timestamptz default now();

-- Atualiza o timestamp de alteração sem depender de extensões externas.
create or replace function public.touch_member_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists members_touch_updated_at on public.members;
create trigger members_touch_updated_at before update on public.members
for each row execute function public.touch_member_updated_at();

-- O backend deve ser a única camada autorizada a ler/escrever estas tabelas.
-- Configure SUPABASE_URL e SUPABASE_SECRET_KEY na Vercel.

-- Para instalações novas, a tabela members já nasce com as colunas acima;
-- os ALTERs tornam a migração segura para um projeto parcialmente criado.

-- Nota: se o editor acusar que username/user_id não aceita null após uma execução parcial,
-- crie as tabelas novamente em um projeto vazio ou ajuste os valores antes de aplicar NOT NULL.

alter table public.members alter column user_id set not null;
alter table public.members alter column username set not null;
alter table public.members alter column first_seen_at set default now();
alter table public.members alter column last_seen_at set default now();
alter table public.members alter column total_seconds set default 0;
alter table public.members alter column status set default 'active';
alter table public.members alter column updated_at set default now();

-- Compatibilidade com consultas do backend.
